In [16]:
from selenium import webdriver
import chromedriver_binary
import pandas as pd

driver = webdriver.Chrome()

In [25]:
driver.get('http://www.espn.com/nba/history/awards/_/id/34')

In [26]:
seasons = []
teams = []

for i in range(40):
    elem = driver.find_element_by_xpath('//*[@id="my-players-table"]/div[1]/div/table/tbody/tr[{}]/td[1]'.format(i+3))
    season = elem.text
    seasons.append(season)
    
for i in range(40):
    elem = driver.find_element_by_xpath('//*[@id="my-players-table"]/div[1]/div/table/tbody/tr[{}]/td[3]'.format(i+3))
    team = elem.text
    teams.append(team)

/var/folders/9g/_t0rc8jx1x39gdxhtwx6q1vw0000gn/T/ipykernel_24844/3880130496.py:5: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  elem = driver.find_element_by_xpath('//*[@id="my-players-table"]/div[1]/div/table/tbody/tr[{}]/td[1]'.format(i+3))
/var/folders/9g/_t0rc8jx1x39gdxhtwx6q1vw0000gn/T/ipykernel_24844/3880130496.py:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  elem = driver.find_element_by_xpath('//*[@id="my-players-table"]/div[1]/div/table/tbody/tr[{}]/td[3]'.format(i+3))

In [27]:
teams

['New York Knicks',
 'Toronto Raptors',
 'Milwaukee Bucks',
 'Toronto Raptors',
 'Houston Rockets',
 'Golden State Warriors',
 'Atlanta Hawks',
 'San Antonio Spurs',
 'Denver Nuggets',
 'San Antonio Spurs',
 'Chicago Bulls',
 'Oklahoma City Thunder',
 'Cleveland Cavaliers',
 'New Orleans Hornets',
 'Toronto Raptors',
 'Dallas Mavericks',
 'Phoenix Suns',
 'Memphis Grizzlies',
 'Memphis Grizzlies',
 'San Antonio Spurs',
 'Detroit Pistons',
 'Philadelphia 76ers',
 'Orlando Magic',
 'Portland Trail Blazers',
 'Indiana Pacers',
 'Miami Heat',
 'Chicago Bulls',
 'Los Angeles Lakers',
 'Atlanta Hawks',
 'New York Knicks',
 'Golden State Warriors',
 'Houston Rockets',
 'Los Angeles Lakers',
 'Phoenix Suns',
 'Denver Nuggets',
 'Portland Trail Blazers',
 'Atlanta Hawks',
 'Milwaukee Bucks',
 'Utah Jazz',
 'Milwaukee Bucks']

In [28]:
coy_season = pd.DataFrame(seasons, columns=['season'])
coy_team = pd.DataFrame(teams, columns=['team'])
coy_df = pd.concat([coy_season, coy_team], axis=1)
coy_df

   season                    team
0    2021         New York Knicks
1    2020         Toronto Raptors
2    2019         Milwaukee Bucks
3    2018         Toronto Raptors
4    2017         Houston Rockets
5    2016   Golden State Warriors
6    2015           Atlanta Hawks
7    2014       San Antonio Spurs
8    2013          Denver Nuggets
9    2012       San Antonio Spurs
10   2011           Chicago Bulls
11   2010   Oklahoma City Thunder
12   2009     Cleveland Cavaliers
13   2008     New Orleans Hornets
14   2007         Toronto Raptors
15   2006        Dallas Mavericks
16   2005            Phoenix Suns
17   2004       Memphis Grizzlies
18   2003       Memphis Grizzlies
19              San Antonio Spurs
20   2002         Detroit Pistons
21   2001      Philadelphia 76ers
22   2000           Orlando Magic
23   1999  Portland Trail Blazers
24   1998          Indiana Pacers
25   1997              Miami Heat
26   1996           Chicago Bulls
27   1995      Los Angeles Lakers
28   1994           Atlanta Hawks
29   1993         New York Knicks
30   1992   Golden State Warriors
31   1991         Houston Rockets
32   1990      Los Angeles Lakers
33   1989            Phoenix Suns
34   1988          Denver Nuggets
35   1987  Portland Trail Blazers
36   1986           Atlanta Hawks
37   1985         Milwaukee Bucks
38   1984               Utah Jazz
39   1983         Milwaukee Bucks

In [21]:
coy_df['season'].unique()

array(['2021', '2020', '2019', '2018', '2017', '2016', '2015', '2014',
       '2013', '2012', '2011', '2010', '2009', '2008', '2007', '2006',
       '2005', '2004', '2003', '', '2002', '2001', '2000', '1999', '1998',
       '1997', '1996', '1995', '1994', '1993', '1992', '1991', '1990',
       '1989', '1988', '1987', '1986', '1985', '1984', '1983'],
      dtype=object)

In [29]:
coy_df = coy_df.replace('', '2003')
coy_df

   season                    team
0    2021         New York Knicks
1    2020         Toronto Raptors
2    2019         Milwaukee Bucks
3    2018         Toronto Raptors
4    2017         Houston Rockets
5    2016   Golden State Warriors
6    2015           Atlanta Hawks
7    2014       San Antonio Spurs
8    2013          Denver Nuggets
9    2012       San Antonio Spurs
10   2011           Chicago Bulls
11   2010   Oklahoma City Thunder
12   2009     Cleveland Cavaliers
13   2008     New Orleans Hornets
14   2007         Toronto Raptors
15   2006        Dallas Mavericks
16   2005            Phoenix Suns
17   2004       Memphis Grizzlies
18   2003       Memphis Grizzlies
19   2003       San Antonio Spurs
20   2002         Detroit Pistons
21   2001      Philadelphia 76ers
22   2000           Orlando Magic
23   1999  Portland Trail Blazers
24   1998          Indiana Pacers
25   1997              Miami Heat
26   1996           Chicago Bulls
27   1995      Los Angeles Lakers
28   1994           Atlanta Hawks
29   1993         New York Knicks
30   1992   Golden State Warriors
31   1991         Houston Rockets
32   1990      Los Angeles Lakers
33   1989            Phoenix Suns
34   1988          Denver Nuggets
35   1987  Portland Trail Blazers
36   1986           Atlanta Hawks
37   1985         Milwaukee Bucks
38   1984               Utah Jazz
39   1983         Milwaukee Bucks

In [30]:
coy_df.to_csv('coy.csv')