In [1]:
from selenium import webdriver
import chromedriver_binary
import pandas as pd

driver = webdriver.Chrome()

In [2]:
driver.get('http://www.espn.com/nba/history/awards/_/id/39')

In [3]:
n = driver.find_elements_by_class_name('oddrow')

seasons = []
teams = []

for i in range(len(n)):
    elem = driver.find_element_by_xpath('//*[@id="my-players-table"]/div[1]/div/table/tbody/tr[{}]/td[1]'.format(i+3))
    season = elem.text
    seasons.append(season)
    
for i in range(len(n)):
    elem = driver.find_element_by_xpath('//*[@id="my-players-table"]/div[1]/div/table/tbody/tr[{}]/td[4]'.format(i+3))
    team = elem.text
    teams.append(team)

/var/folders/9g/_t0rc8jx1x39gdxhtwx6q1vw0000gn/T/ipykernel_24241/2868661025.py:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  n = driver.find_elements_by_class_name('oddrow')
/var/folders/9g/_t0rc8jx1x39gdxhtwx6q1vw0000gn/T/ipykernel_24241/2868661025.py:7: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  elem = driver.find_element_by_xpath('//*[@id="my-players-table"]/div[1]/div/table/tbody/tr[{}]/td[1]'.format(i+3))
/var/folders/9g/_t0rc8jx1x39gdxhtwx6q1vw0000gn/T/ipykernel_24241/2868661025.py:12: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  elem = driver.find_element_by_xpath('//*[@id="my-players-table"]/div[1]/div/table/tbody/tr[{}]/td[4]'.format(i+3))

In [5]:
dpoy_season = pd.DataFrame(seasons, columns=['season'])
dpoy_team = pd.DataFrame(teams, columns=['team'])
dpoy_df = pd.concat([dpoy_season, dpoy_team], axis=1)
dpoy_df

   season                   team
0    2021              Utah Jazz
1    2020        Milwaukee Bucks
2    2019              Utah Jazz
3    2018              Utah Jazz
4    2017  Golden State Warriors
5    2016      San Antonio Spurs
6    2015      San Antonio Spurs
7    2014          Chicago Bulls
8    2013      Memphis Grizzlies
9    2012        New York Knicks
10   2011          Orlando Magic
11   2010          Orlando Magic
12   2009          Orlando Magic
13   2008         Boston Celtics
14   2007         Denver Nuggets
15   2006        Detroit Pistons
16   2005        Detroit Pistons
17   2004         Indiana Pacers
18   2003        Detroit Pistons
19   2002        Detroit Pistons
20   2001     Philadelphia 76ers
21   2000             Miami Heat
22   1999             Miami Heat
23   1998          Atlanta Hawks
24   1997          Atlanta Hawks
25   1996    Seattle SuperSonics
26   1995         Denver Nuggets
27   1994        Houston Rockets
28   1993        Houston Rockets
29   1992      San Antonio Spurs
30   1991        Detroit Pistons
31   1990        Detroit Pistons
32   1989              Utah Jazz
33   1988          Chicago Bulls
34   1987     Los Angeles Lakers
35   1986      San Antonio Spurs
36   1985              Utah Jazz
37   1984        Milwaukee Bucks
38   1983        Milwaukee Bucks

In [6]:
dpoy_df.to_csv('dpoy.csv')