In [2]:
from selenium import webdriver
import chromedriver_binary
import pandas as pd
import time

driver = webdriver.Chrome()

In [3]:
driver.get('http://www.espn.com/nba/history/awards/_/id/40')

In [4]:
n = driver.find_elements_by_class_name('oddrow')

seasons = []
teams = []

for i in range(len(n)):
    elem = driver.find_element_by_xpath('//*[@id="my-players-table"]/div[1]/div/table/tbody/tr[{}]/td[1]'.format(i+3))
    season = elem.text
    seasons.append(season)
    
for i in range(len(n)):
    elem = driver.find_element_by_xpath('//*[@id="my-players-table"]/div[1]/div/table/tbody/tr[{}]/td[4]'.format(i+3))
    team = elem.text
    teams.append(team)

/var/folders/9g/_t0rc8jx1x39gdxhtwx6q1vw0000gn/T/ipykernel_23753/2868661025.py:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  n = driver.find_elements_by_class_name('oddrow')
/var/folders/9g/_t0rc8jx1x39gdxhtwx6q1vw0000gn/T/ipykernel_23753/2868661025.py:7: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  elem = driver.find_element_by_xpath('//*[@id="my-players-table"]/div[1]/div/table/tbody/tr[{}]/td[1]'.format(i+3))
/var/folders/9g/_t0rc8jx1x39gdxhtwx6q1vw0000gn/T/ipykernel_23753/2868661025.py:12: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  elem = driver.find_element_by_xpath('//*[@id="my-players-table"]/div[1]/div/table/tbody/tr[{}]/td[4]'.format(i+3))

In [11]:
smoy_season = pd.DataFrame(seasons, columns=['season'])

In [12]:
smoy_team = pd.DataFrame(teams, columns=['team'])

In [13]:
smoy_df = pd.concat([smoy_season, smoy_team], axis=1)
smoy_df

   season                    team
0    2021               Utah Jazz
1    2020             LA Clippers
2    2019             LA Clippers
3    2018             LA Clippers
4    2017         Houston Rockets
5    2016             LA Clippers
6    2015         Toronto Raptors
7    2014             LA Clippers
8    2013         New York Knicks
9    2012   Oklahoma City Thunder
10   2011      Los Angeles Lakers
11   2010           Atlanta Hawks
12   2009        Dallas Mavericks
13   2008       San Antonio Spurs
14   2007            Phoenix Suns
15   2006       Memphis Grizzlies
16   2005           Chicago Bulls
17   2004        Dallas Mavericks
18   2003        Sacramento Kings
19   2002         Detroit Pistons
20   2001      Philadelphia 76ers
21   2000            Phoenix Suns
22   1999           Orlando Magic
23   1998            Phoenix Suns
24   1997         New York Knicks
25   1996           Chicago Bulls
26   1995         New York Knicks
27   1994       Charlotte Hornets
28   1993  Portland Trail Blazers
29   1992          Indiana Pacers
30   1991          Indiana Pacers
31   1990         Milwaukee Bucks
32   1989            Phoenix Suns
33   1988        Dallas Mavericks
34   1987         Milwaukee Bucks
35   1986          Boston Celtics
36   1985          Boston Celtics
37   1984          Boston Celtics
38   1983      Philadelphia 76ers

In [14]:
smoy_df.to_csv('smoy.csv')